export enum GameEvent {
    CREATE_GAME_EVENT = 'createGame',
    JOIN_GAME_EVENT = 'joinGame',
    START_GAME_EVENT = 'startGame',
    CANCEL_GAME_EVENT = 'cancelGame',
    TOGGLE_GAME_LOCK_EVENT = 'toggleGameLock',
    QCM_SUBMIT_EVENT = 'qcmSubmit',
    NEXT_QUESTION_EVENT = 'nextQuestion',
    QCM_TOGGLE_CHOICE_EVENT = 'qcmToggleChoice',
    END_GAME_EVENT = 'endGame',
    QRL_INPUT_CHANGE_EVENT = 'qrlInputChange',
    QRL_SUBMIT_EVENT = 'qrlSubmit',
    QRL_EVALUATE_EVENT = 'qrlEvaluate',
    ERROR_EVENT = 'error',
}