export const MIN_CHOICE_COUNT = 2;
export const MAX_CHOICE_COUNT = 4;
export const POINT_VALUE_BASE_MULTIPLE = 10;
export const SNACK_MESSAGE_DURATION = 2000;
export const MIN_QCM_COUNT_ENABLE_RANDOM_MODE = 5;
